// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID        int        `json:"id"`
	AuthorID  uuid.UUID  `json:"authorID"`
	PostID    int        `json:"postID"`
	ParentID  *int       `json:"parentID,omitempty"`
	Content   string     `json:"content"`
	CreatedAt time.Time  `json:"created_at"`
	Replies   []*Comment `json:"replies"`
	Depth     int32      `json:"depth"`
}

type Mutation struct {
}

type NewComment struct {
	AuthorID uuid.UUID `json:"authorID"`
	PostID   int       `json:"postID"`
	ParentID *int      `json:"parentID,omitempty"`
	Content  string    `json:"content"`
}

type NewPost struct {
	AuthorID        uuid.UUID `json:"authorID"`
	Title           string    `json:"title"`
	Content         string    `json:"content"`
	CommentsAllowed bool      `json:"commentsAllowed"`
}

type Post struct {
	ID              int        `json:"id"`
	AuthorID        uuid.UUID  `json:"authorID"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	CommentsAllowed bool       `json:"commentsAllowed"`
	Comments        []*Comment `json:"comments"`
	CreatedAt       time.Time  `json:"created_at"`
}

type Query struct {
}

type Subscription struct {
}
