// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID         int        `json:"id"`
	PostID     int        `json:"postID"`
	AuthorID   uuid.UUID  `json:"authorID"`
	Text       string     `json:"text"`
	CreateDate time.Time  `json:"createDate"`
	ParentID   *int       `json:"parentID,omitempty"`
	Replies    []*Comment `json:"replies"`
}

type Mutation struct {
}

type NewComment struct {
	AuthorID uuid.UUID `json:"authorID"`
	PostID   string    `json:"postID"`
	ParentID *string   `json:"parentID,omitempty"`
	Content  string    `json:"content"`
}

type NewPost struct {
	AuthorID        uuid.UUID `json:"authorID"`
	Title           string    `json:"title"`
	Content         string    `json:"content"`
	CommentsEnabled bool      `json:"commentsEnabled"`
}

type Post struct {
	ID              int        `json:"id"`
	AuthorID        uuid.UUID  `json:"authorID"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	CommentsAllowed bool       `json:"commentsAllowed"`
	CreateDate      time.Time  `json:"createDate"`
	Comments        []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
